FROM husseinabdallah2/mpi4py-cluster:master 

LABEL maintainer="DSD Team 18"

# set Docker image build arguments
# build arguments for user/group configurations
ARG USER=team18
ARG USER_ID=802
ARG USER_GROUP=team18
ARG USER_GROUP_ID=802
ARG USER_HOME=/home/dsd
#] build argument for MOTD
ARG MOTD='DSD Assignment'
ENV ENV=${USER_HOME}"/.ashrc"

# create the non-root user and group and set MOTD login message
RUN \
    groupadd --system -g ${USER_GROUP_ID} ${USER_GROUP} \
    && useradd --system --create-home --home-dir ${USER_HOME} --no-log-init -g ${USER_GROUP_ID} -u ${USER_ID} ${USER} \
    && echo '[ ! -z "${TERM}" -a -r /etc/motd ] && cat /etc/motd' >> /etc/bash.bashrc; echo "${MOTD}" > /etc/motd

RUN apt-get update
RUN apt-get install unzip

# set the user and work directory

RUN mkdir ${USER_HOME}/shared

# copy app to user home
COPY --chown=team18:team18 ./DistributedProcessisingSystem ${USER_HOME}/shared/
# copy entry to user home
COPY --chown=team18:team18 ./entry ${USER_HOME}/

RUN whoami
USER 802
RUN whoami
WORKDIR ${USER_HOME}

RUN chown 802:802 /home/dsd/dsd-entrypoint.sh

RUN chmod +x /home/dsd/dsd-entrypoint.sh
# set environment variables
ENV WORKING_DIRECTORY=${USER_HOME} 
# expose ports
EXPOSE 22

# initiate container and run the python server
#CMD python /home/team18/Server.py
#ENTRYPOINT ["tail", "-f", "/dev/null"]
ENTRYPOINT ["sh","/home/dsd/dsd-entrypoint.sh"]